name: Publish Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: PCCOOLER-LCD-Control-*
          merge-multiple: true
          path: artifacts

      - uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**
          generate_release_notes: true
